### ISSUE TITLE
It's all resource pricing?

### ISSUE THREAD

**Issue by s-tikhomirov** [waku-org/research#27]
There is a talk from EthCC that made a lasting impression on me and I think is quite relevant:

https://www.youtube.com/watch?v=YoWMLoeQGeI

TLDR: incentivization in blockchains is about fairly rewarding actors for the resources they spend. The question is: what resources exactly and how to quantify them?

We can approach our incentivization question (#21) from a similar angle. Currently, clients occupy the server's resources but don't pay for that, such as:

- time x storage (size in bytes? number of messages?)
- CPU cycles for processing requests
- network bandwidth

TODO: think about how to quantify these resources, are there others, etc.

**Comment by alrevuelta** [comment]
Agree on "fairly rewarding actors for the resources they spend" but there is another set that is "resources that you can proove you spent". And imho we should look at the intersection of both sets.

For example, prooving that you are spending "x bandwidth" is not trivial. Same for CPU. So perhaps we should look into things that are easy to proove and that indirectly represent your "efforts".

An example I like a lot is the Ethereum one. No one incentivices you for gossiping blocks, attestations, storing blocks, or even serving them to new nodes syncing. But people do it because its a requirement for other higher level duties that are incentiviced.

**Comment by s-tikhomirov** [comment]
> things that are easy to prove and that indirectly represent your "efforts"

I agree, one caveat though is that the gap between what I actually spend and what I use as a proxy to prove what I've spent can be exploited by attackers.

**Comment by s-tikhomirov** [comment]
Closing in favor of #35.
